version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: express-sequelize-postgres/node_app
    ports:
      - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
    depends_on:
      - node_db
    command: npm run start

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}